## @file
# Mergify YML file that automatically merges a GitHub pull request against
# edk2-ci if all of the GitHub branch protections have passed.  It also
# contains rules to auto close branches that are not from an EDK II Maintainer
# and post a comment on pull requests that have merge conflicts.
#
# * Update the 'base=edk2-ci' statements with the name of the branch to merge
#   pull requests.
#
# * Update the 'status-failure' statement with the name of the name of the Azure
#   Pipelines Build that performs the EDK II Maintainer check.
#
# * This file must be checked into the 'default' branch of a repo.  Copies
#   of this file on other branches of a repo are ignored by Mergify.
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# https://github.com/apps/mergify
# https://doc.mergify.io/
#
##

pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - base=edk2-ci
    actions:
      merge:
        strict: true
        method: rebase
  - name: post a comment on a PR that can not be merged due to a merge conflict
    conditions:
      - base=edk2-ci
      - conflict
    actions:
      comment:
        message: PR can not be merged due to conflict.  Please rebase and resubmit
  - name: automatically close a PR that fails the EDK II Maintainers membership check
    conditions:
      - base=edk2-ci
      - status-failure=tianocore.edk2-staging
    actions:
      close:
        message: PR submitter is not a member of the Tianocore EDK II Maintainers team
